name: lemonator
summary: AI-powered character guessing game with visual generation
version: 1.0.0
description: |
  Lemonators is an intelligent character guessing game powered by AI. Think of any 
  real or fictional character, and the AI detective will ask strategic questions to 
  identify who you're thinking of. As you answer, the app generates a unique visual 
  portrait of your character using AI image generation.

  **Key Features**

  * Smart question generation 
  * Wikipedia integration for discovering famous personalities
  * Logical deduction engine that learns from your answers
  * Confidence scoring to determine optimal guess timing
  * Beautiful Electron desktop interface with React

  **Requirements**

  This snap requires the lemonade-server snap to be installed and running on 
  localhost:8080. The server provides the SDXL-Turbo image generation, Qwen3-4B, and Phi-4-mini models.

  To install both:

    sudo snap install lemonator
    sudo snap install lemonade-server

  **How to Play**

  1. Think of any character (real or fictional)
  2. Answer yes/no/probably/probably not/I don't know questions from the AI detective
  3. Watch as the AI narrows down possibilities
  4. See if the AI can guess your character correctly!

  The AI combines database searching, Wikipedia discovery, and logical reasoning
  to identify characters in as few questions as possible.

adopt-info: lemonator
grade: stable
confinement: strict
base: core24
contact: https://github.com/phqen1x/lemonator/issues
issues: https://github.com/phqen1x/lemonator/issues
website: https://github.com/phqen1x/lemonator
license: MIT
compression: lzo

platforms:
  amd64:

parts:
  lemonator:
    plugin: nil
    source: .
    build-snaps:
      - node/22/stable
    build-packages:
      - git
    override-pull: |
      craftctl default
      VERSION=$(craftctl get version)
      if [ -z $VERSION ]; then
        VERSION=$(git describe --tags --abbrev=10)
        craftctl set version=$VERSION
      fi
    override-build: |
      set +u # For unbound variables
      # workaround for build.snapcraft.io builds
      # https://bugs.launchpad.net/bugs/1886861
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi

      npm install
      npm run electron:build:linux
      cp -rp release/linux-unpacked $CRAFT_PART_INSTALL/
    prime:
      - linux-unpacked
      - -*/chrome-sandbox
      - -*/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
      - -*/resources/app.asar.unpacked/node_modules/sharp/vendor/include

  scripts:
    plugin: dump
    source: scripts
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp launcher $CRAFT_PART_INSTALL/bin/
      chmod a+x $CRAFT_PART_INSTALL/bin/launcher

  cleanup:
    after: [ lemonator ]
    plugin: nil
    build-snaps: [ gnome-46-2404 ]
    override-prime: |
        set -eux
        cd /snap/gnome-46-2404/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

plugs:
  shmem:
    interface: shared-memory
    private: true
  lemonade-server:
    interface: content
    content: foo
    target: $SNAP_DATA/foo
    default-provider: lemonade-server

apps:
  lemonator:
    extensions: [gnome]
    command: bin/launcher
    plugs:
      - network
      - shmem
    environment:
      GTK_USE_PORTAL: 1
      TMPDIR: $XDG_RUNTIME_DIR
      HOME: $SNAP_USER_COMMON
